### ISSUE TITLE
Error when using `requests` as a request backend (easy fix)

### ISSUE THREAD

**Issue by jamespayor** [SnapSearch/SnapSearch-Client-Python#3]
Running python 3, `requests==2.12.4`, requests throws an error when validating the message headers.

In `backend.py`, `_build_message` returns an integer for the `"Content-Length"` header. The `requests` library doesn't like this.

Consider replacing `len(payload)` with `str(len(payload))` - this fixes the problem.

**Comment by jamespayor** [comment]
(ala [this commit](https://github.com/jamespayor/SnapSearch-Client-Python/commit/7e880ca7797f579b907ffe633ef363aa172496e3))

**Comment by CMCDragonkai** [comment]
Hey feel free to send over a PR, and I'll accept. That goes for the other issues you created as well.
